version: '3'
services:
  couchdb:
    image: couchdb
    container_name: einkaufv-couchdb
    ports:
      - 5984:5984
    volumes:
      - ./data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
