name: Karma Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '21'
    - name: Run Karma Tests
      run: |
        cd app/
        npm install
        npm run test